export enum EventoType {
	LOGIN_ATTEMPT = 'INTENTO_LOGIN',
	LOGIN_ATTEMPT_FAILURE = 'FALLO_LOGIN',
	LOGIN_ATTEPMT_SUCCESS = 'EXITO_LOGIN',
	PROFILE_UPDATE = 'ACTUALIZACION_PERFIL',
	PROFILE_PICTURE_UPDATE = 'ACTUALIZACION_FOTO_PERFIL',
	ROLE_UPDATE = 'ACTUALIZACION_ROL',
	ACCOUNT_SETTINGS_UPDATE= 'ACTUALIZACION_CONFIGURACION_CUENTA',
	PASSWORD_UPDATE ='ACTUALIZACION_CONTRASENA',
	MFA_UPDATE = 'ACTUALIZACION_MFA'
}
